---
git_ref: master
cache_dir: /tmp/.jtaf_cache
junos_config_xml: test_data/test.xml
junos_family: junos-es
junos_version: 23.1R1
yang_patches:
  - original_git_sha: 0acaaa26d84570516d6983a4d9211969b743b916
    required_sha_256: 07ef6ddc587977d652ecdc9a0b84486171da34cda7081ff78578c1542addf73a
    diff: |
      diff --git a/23.1/23.1R1/junos/conf/junos-conf-system@2023-01-01.yang b/23.1/23.1R1/junos/conf/junos-conf-system@2023-01-01.yang
      index 0acaaa26..5d699f50 100644
      --- a/23.1/23.1R1/junos/conf/junos-conf-system@2023-01-01.yang
      +++ b/23.1/23.1R1/junos/conf/junos-conf-system@2023-01-01.yang
      @@ -7185,7 +7185,6 @@
              container traceoptions {
                description "Autoconfiguration trace options";
                status deprecated;
      -         uses autoconf_traceoptions_type;
              }
            }
            container processes {
github_yang_paths:
  22.4R1:
    junos:
      - 22.4/22.4R1/common
      - 22.4/22.4R1/junos/conf
    junos-es:
      - 22.4/22.4R1/common
      - 22.4/22.4R1/junos-es/conf
    junos-ex:
      - 22.4/22.4R1/common
      - 22.4/22.4R1/junos-ex/conf
    junos-qfx:
      - 22.4/22.4R1/common
      - 22.4/22.4R1/junos-qfx/conf
  23.1R1:
    junos:
      - 23.1/23.1R1/common
      - 23.1/23.1R1/junos/conf
    junos-es:
      - 23.1/23.1R1/common
      - 23.1/23.1R1/junos-es/conf
    junos-ex:
      - 23.1/23.1R1/common
      - 23.1/23.1R1/junos-ex/conf
    junos-qfx:
      - 23.1/23.1R1/common
      - 23.1/23.1R1/junos-qfx/conf
