package yang

import "github.com/chrismarget-j/jtaf/data/yang/ietf"

// this code generated by data/yang/generator/main.go - DO NOT EDIT

func init() {
	Files["ietf/ietf-yang-metadata@2016-08-05.yang"] = ietf.YANG1f9c874d09882c4d34f9e8f1c4bb058ff0909c0f47516dcab01780248c738e27
}
